version: '3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
