version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - '3000:3000'

  migration:
    build:
      context: .
    command: ['./wait-for-it/wait-for-it.sh', 'db:5432', '--', 'yarn', 'db']
    environment:
      DB_USER: postgres
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_PASSWORD: pass
      DB_HOST: db
      NODE_ENV: production
    links:
      - db
    depends_on:
      - db
